version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - data_volume:/app/data
  lint:
    build:
      context: .
      dockerfile: Dockerfile.lint
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - data_test_volume:/app/data
volumes:
  data_volume:
  data_test_volume:
